# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    reviewers:
      - infinite-automations/admins
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      # Check for updates to terraform every week
      interval: "weekly"
    reviewers:
      - infinite-automations/admins
  - package-ecosystem: "terraform"
    directory: "examples/full"
    schedule:
      # Check for updates to terraform every week
      interval: "weekly"
    reviewers:
      - infinite-automations/admins
  - package-ecosystem: "terraform"
    directory: "test/create-resource"
    schedule:
      # Check for updates to terraform every week
      interval: "weekly"
    reviewers:
      - infinite-automations/admins
