# .terraform-docs.yml
formatter: "markdown table"

sections:
  show:
    - header
    - requirements
    - providers
    - resources
    - inputs
    - outputs
    - footer

content: |-
  {{ .Header }}

  ## Module Usage

  ```hcl
  {{ include "examples/full/main.tf" }}
  ```

  For a detailed documentation see the [full example](examples/full/README.md)

  ## Github Workflow Example

  ```hcl
  {{ include "examples/github/example.yml" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  required: true
  type: true
  hide-empty: true
  indent: 2
