name: TFLint

description: "Scan Terraform Configuration Files"

inputs:
  version:
    description: "The version of TFLint to use"
    required: false
    default: "latest"
  directory:
    description: "The directory where the Terraform configuration files are located"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: ${{ inputs.version }}
    - name: Show version
      run: tflint --version
      shell: bash
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
    - name: Run TFLint
      run: tflint -f compact
      working-directory: ${{ inputs.directory }}
      shell: bash
